AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Users Management API

Parameters:
  EnvStageName:
    Default: dev
    Description: The Environment name (e.g. dev, prod, etc.)
    Type: String
  Region:
    Default: us-east-1
    Description: The region to deploy the managed services
    Type: String
  StackName:
    Type: String
    Default: creze-test-stack
    Description: The name of the stack
  RoleName:
    Type: String
    Default: atenea-role
    Description: The default role name given to to apply to the functions
  GitHubRepoName:
    Type: String
    Default: cr_tech_test
    Description: The name of the GitHub repository

Mappings:
  LambdaAuthorizerSecrets:
    local:
      SMLAMBDAAUTHORIZERCOGNITO: "lambda-authorizher-cognito-local"
    dev:
      SMLAMBDAAUTHORIZERCOGNITO: "lambda-authorizher-cognito-dev"
    qa:
      SMLAMBDAAUTHORIZERCOGNITO: "lambda-authorizher-cognito-qa"
    prod:
      SMLAMBDAAUTHORIZERCOGNITO: "lambda-authorizher-cognito-prod"
  LogLevels:
    local:
      LOGLEVEL: "DEBUG"
    dev:
      LOGLEVEL: "DEBUG"
    qa:
      LOGLEVEL: "INFO"
    prod:
      LOGLEVEL: "INFO"

Globals:
  Function:
    MemorySize: 128
    Timeout: 600
    Environment:
      Variables:
        REGION: !Ref "Region"
        ENV_NAME: !Ref "EnvStageName"
        LOG_LEVEL: !FindInMap [LogLevels, !Ref EnvStageName, LOGLEVEL]

Resources:
  LambdaSignInFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      FunctionName:
        Fn::Sub: ${AWS::StackName}-LambdaSignInFunction-${EnvStageName}
      MemorySize: 128
      Environment:
        Variables:
          SMLAMBDAAUTHORIZERCOGNITO: !FindInMap
            - LambdaAuthorizerSecrets
            - !Ref EnvStageName
            - SMLAMBDAAUTHORIZERCOGNITO

      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: Any
    Metadata:
      DockerTag: !Sub "${AWS::StackName}-LambdaSignInFunction-${EnvStageName}"
      DockerContext: ./lambdas/auth/
      Dockerfile: Dockerfile

Conditions:
  IsLocal:
    Fn::Equals:
      - !Ref EnvStageName
      - "local"
